/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;

import casino.controlador.ControladorConfiguracion;
import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 *
 * @author BANGHO
 */
public class VentanaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
        this.controlador = new ControladorConfiguracion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPartidas = new javax.swing.ButtonGroup();
        panelConfiguracion = new javax.swing.JPanel();
        lblDineroInicial = new javax.swing.JLabel();
        txtDineroInicial = new javax.swing.JTextField();
        llbCantidaPartidas = new javax.swing.JLabel();
        optPartidas3 = new javax.swing.JRadioButton();
        optPartidas5 = new javax.swing.JRadioButton();
        optPartidas2 = new javax.swing.JRadioButton();
        panelRegistroJugadores1 = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        txtApodo = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblJugadores = new javax.swing.JLabel();
        cmbTipoJugador = new javax.swing.JComboBox<>();
        btnEliminarJugador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstJugadores = new javax.swing.JList<>();
        lblApodo = new javax.swing.JLabel();
        btnAgregarJugador = new javax.swing.JButton();
        btnCargarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casino de Dados - Configuración");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConfiguracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de Partida"));
        panelConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDineroInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDineroInicial.setText("Dinero Inicial");
        panelConfiguracion.add(lblDineroInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtDineroInicial.setText("500");
        panelConfiguracion.add(txtDineroInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        llbCantidaPartidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llbCantidaPartidas.setText("Partidas");
        panelConfiguracion.add(llbCantidaPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        bgPartidas.add(optPartidas3);
        optPartidas3.setSelected(true);
        optPartidas3.setText("3");
        panelConfiguracion.add(optPartidas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        bgPartidas.add(optPartidas5);
        optPartidas5.setText("5");
        panelConfiguracion.add(optPartidas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        bgPartidas.add(optPartidas2);
        optPartidas2.setText("2");
        panelConfiguracion.add(optPartidas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        getContentPane().add(panelConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 90));

        panelRegistroJugadores1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Jugadores"));
        panelRegistroJugadores1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegistroJugadores1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");
        panelRegistroJugadores1.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        panelRegistroJugadores1.add(txtApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        lblNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre2.setText("Nombre");
        panelRegistroJugadores1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        panelRegistroJugadores1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, -1));

        lblJugadores.setText("Jugadores");
        panelRegistroJugadores1.add(lblJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        cmbTipoJugador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novato", "Experto", "VIP", "Casino" }));
        cmbTipoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoJugadorActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(cmbTipoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, -1));

        btnEliminarJugador.setText("Eliminar Jugador");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(btnEliminarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        lstJugadores.setToolTipText("");
        jScrollPane3.setViewportView(lstJugadores);

        panelRegistroJugadores1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 80));

        lblApodo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApodo.setText("Apodo");
        panelRegistroJugadores1.add(lblApodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnAgregarJugador.setText("Agregar Jugador");
        btnAgregarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugadorActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(btnAgregarJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        getContentPane().add(panelRegistroJugadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 330, 270));

        btnCargarPartida.setText("Cargar Partida");
        btnCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 130, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 30));

        btnIniciarJuego.setText("Iniciar Juego");
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        int indice = lstJugadores.getSelectedIndex();
        controlador.eliminarJugador(indice);
    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
        mostrarMensaje("Funcionalidad en desarrollo");
        //Todavía no está porque implementa carga de partidas guardad y requiere implementar GestorPersistencia
    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    private void btnAgregarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugadorActionPerformed
        String nombre = txtNombre.getText().trim();
        String apodo = txtApodo.getText().trim();
        String tipo = (String) cmbTipoJugador.getSelectedItem();
        
        controlador.agregarJugador(nombre, apodo, tipo);
    }//GEN-LAST:event_btnAgregarJugadorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        controlador.salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        try {
            int dineroInicial = Integer.parseInt(txtDineroInicial.getText());
            int cantidadPartidas = 3; // Por defecto

            if (optPartidas2.isSelected()) {
                cantidadPartidas = 2;
            } else if (optPartidas5.isSelected()) {
                cantidadPartidas = 5;
            }

            controlador.iniciarJuego(dineroInicial, cantidadPartidas);
        } catch (NumberFormatException e) {
            mostrarError("El dinero inicial debe ser un número válido");
        }
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConfiguracion().setVisible(true);
            }
        }); 
    }
    // Controlador
    private ControladorConfiguracion controlador;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPartidas;
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoJugador;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblDineroInicial;
    private javax.swing.JLabel lblJugadores;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel llbCantidaPartidas;
    private javax.swing.JList<String> lstJugadores;
    private javax.swing.JRadioButton optPartidas2;
    private javax.swing.JRadioButton optPartidas3;
    private javax.swing.JRadioButton optPartidas5;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelRegistroJugadores1;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtDineroInicial;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    // Métodos públicos para el controlador
    public JList<String> getLstJugadores() {
        return lstJugadores;
    }
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void limpiarCampos() {
        txtNombre.setText("");
        txtApodo.setText("");
        cmbTipoJugador.setSelectedIndex(0);
    }

}
