/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;
import casino.controlador.ControladorVentanaReporte;
import casino.modelo.PartidaModelo;  

/**
 *
 * @author BANGHO
 */
public class VentanaJuego extends javax.swing.JFrame {
     private final PartidaModelo modelo;
     
     public VentanaJuego(PartidaModelo modelo) {
        this.modelo = modelo;
        initComponents();
    }
     
    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
    }

public void actualizarPanelSuperior(int partidaActual, int totalPartidas, int rondaActual, int pozo) {
        lblPartida.setText(partidaActual + "/" + totalPartidas);
        lblRonda.setText(rondaActual + "/3");
        lblPozo.setText("$" + String.format("%d", pozo)); 
    }

    public void agregarLog(String mensaje) {
        txtLog.append(mensaje + "\n");
        // Auto-scroll
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }

    public javax.swing.JPanel getPanelJugadores() {
        return panelJugadores;
    }

    public void resetearVista() {
        txtLog.setText("");
        panelJugadores.removeAll();
        panelJugadores.revalidate();
        panelJugadores.repaint();
    }

    public javax.swing.JButton getBtnSiguienteRonda() {
        return btnSiguienteRonda;
    }
    public javax.swing.JMenuItem getMenuSalir() {
        return menuSalir;
    }
    
    public javax.swing.JMenuItem getMenuRanking() {
        return menuRanking;
    }

    public javax.swing.JMenuItem getMenuHistorial() {
        return menuHistorial;
    }

    public javax.swing.JMenuItem getMenuEstadisticas() {
        return menuEstadisticas;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblPozo = new javax.swing.JLabel();
        lblPozoTexto = new javax.swing.JLabel();
        lblPartida = new javax.swing.JLabel();
        lblPartidaTexto = new javax.swing.JLabel();
        lblRondaTexto = new javax.swing.JLabel();
        lblRonda = new javax.swing.JLabel();
        panelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        scrollPannel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelJugadores = new javax.swing.JPanel();
        btnSiguienteRonda = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuardarPartida = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRanking = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenuItem();
        menuEstadisticas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la partida"));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPozo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPozo.setText("$0");
        panelSuperior.add(lblPozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 50, -1));

        lblPozoTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPozoTexto.setText("Pozo:");
        panelSuperior.add(lblPozoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, -1));

        lblPartida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPartida.setText("1/5");
        panelSuperior.add(lblPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, -1));

        lblPartidaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPartidaTexto.setText("Partida:");
        panelSuperior.add(lblPartidaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, -1));

        lblRondaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRondaTexto.setText("Ronda:");
        panelSuperior.add(lblRondaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 50, -1));

        lblRonda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRonda.setText("1/3");
        panelSuperior.add(lblRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 50, -1));

        getContentPane().add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 70));

        panelLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log de Eventos"));

        txtLog.setEditable(false);
        txtLog.setColumns(40);
        txtLog.setRows(8);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 440, 180));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        panelJugadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel Jugadores"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrollPannel.setViewportView(jPanel1);

        getContentPane().add(scrollPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 440, 210));

        btnSiguienteRonda.setText("Siguiente Ronda");
        btnSiguienteRonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteRondaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguienteRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, -1));

        btnReportes.setText("Ver Reportes Final");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jMenu1.setText("Partida");

        menuGuardarPartida.setText("Guardar Partida");
        jMenu1.add(menuGuardarPartida);

        menuSalir.setText("Salir");
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");

        menuRanking.setText("Ranking Actual");
        jMenu2.add(menuRanking);

        menuHistorial.setText("Historial de Partidas");
        jMenu2.add(menuHistorial);

        menuEstadisticas.setText("Estadísticas Generales");
        jMenu2.add(menuEstadisticas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteRondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteRondaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteRondaActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
       ControladorVentanaReporte ctrlReporte = new ControladorVentanaReporte(modelo);
    ctrlReporte.mostrar();
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSiguienteRonda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPartida;
    private javax.swing.JLabel lblPartidaTexto;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JLabel lblPozoTexto;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JLabel lblRondaTexto;
    private javax.swing.JMenuItem menuEstadisticas;
    private javax.swing.JMenuItem menuGuardarPartida;
    private javax.swing.JMenuItem menuHistorial;
    private javax.swing.JMenuItem menuRanking;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelJugadores;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollPannel;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
