/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;

/**
 *
 * @author BANGHO
 */
public class VentanaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPartidas = new javax.swing.ButtonGroup();
        panelConfiguracion = new javax.swing.JPanel();
        lblDineroInicial = new javax.swing.JLabel();
        txtDineroInicial = new javax.swing.JTextField();
        llbCantidaPartidas = new javax.swing.JLabel();
        optPartidas3 = new javax.swing.JRadioButton();
        optPartidas5 = new javax.swing.JRadioButton();
        optPartidas2 = new javax.swing.JRadioButton();
        panelRegistroJugadores1 = new javax.swing.JPanel();
        lblTipo1 = new javax.swing.JLabel();
        txtApodo1 = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        lblJugadores1 = new javax.swing.JLabel();
        cmbTipoJugador1 = new javax.swing.JComboBox<>();
        btnEliminarJugador1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstJugadores1 = new javax.swing.JList<>();
        lblApodo2 = new javax.swing.JLabel();
        btnAgregarJugador3 = new javax.swing.JButton();
        btnCargarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIniciarJuego1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casino de Dados - Configuración");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConfiguracion.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de Partida"));
        panelConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelConfiguracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDineroInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDineroInicial.setText("Dinero Inicial");
        panelConfiguracion.add(lblDineroInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtDineroInicial.setText("500");
        panelConfiguracion.add(txtDineroInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        llbCantidaPartidas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        llbCantidaPartidas.setText("Partidas");
        panelConfiguracion.add(llbCantidaPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        bgPartidas.add(optPartidas3);
        optPartidas3.setSelected(true);
        optPartidas3.setText("3");
        panelConfiguracion.add(optPartidas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        bgPartidas.add(optPartidas5);
        optPartidas5.setText("5");
        panelConfiguracion.add(optPartidas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        bgPartidas.add(optPartidas2);
        optPartidas2.setText("2");
        panelConfiguracion.add(optPartidas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        getContentPane().add(panelConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 90));

        panelRegistroJugadores1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Jugadores"));
        panelRegistroJugadores1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelRegistroJugadores1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTipo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo1.setText("Tipo:");
        panelRegistroJugadores1.add(lblTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        panelRegistroJugadores1.add(txtApodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        lblNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre2.setText("Nombre");
        panelRegistroJugadores1.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        panelRegistroJugadores1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, -1));

        lblJugadores1.setText("Jugadores");
        panelRegistroJugadores1.add(lblJugadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        cmbTipoJugador1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTipoJugador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novato", "Experto", "VIP", "Casino" }));
        cmbTipoJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoJugador1ActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(cmbTipoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, -1));

        btnEliminarJugador1.setText("Eliminar Jugador");
        btnEliminarJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugador1ActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(btnEliminarJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        lstJugadores1.setToolTipText("");
        jScrollPane3.setViewportView(lstJugadores1);

        panelRegistroJugadores1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 250, 80));

        lblApodo2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblApodo2.setText("Apodo");
        panelRegistroJugadores1.add(lblApodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnAgregarJugador3.setText("Agregar Jugador");
        btnAgregarJugador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarJugador3ActionPerformed(evt);
            }
        });
        panelRegistroJugadores1.add(btnAgregarJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        getContentPane().add(panelRegistroJugadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 330, 270));

        btnCargarPartida.setText("Cargar Partida");
        btnCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 130, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 30));

        btnIniciarJuego1.setText("Inciar Juego");
        btnIniciarJuego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuego1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarJuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoJugador1ActionPerformed

    private void btnEliminarJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarJugador1ActionPerformed

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    private void btnAgregarJugador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarJugador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarJugador3ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarJuego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarJuego1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPartidas;
    private javax.swing.JButton btnAgregarJugador3;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarJugador1;
    private javax.swing.JButton btnIniciarJuego1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoJugador1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblApodo2;
    private javax.swing.JLabel lblDineroInicial;
    private javax.swing.JLabel lblJugadores1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel llbCantidaPartidas;
    private javax.swing.JList<String> lstJugadores1;
    private javax.swing.JRadioButton optPartidas2;
    private javax.swing.JRadioButton optPartidas3;
    private javax.swing.JRadioButton optPartidas5;
    private javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelRegistroJugadores1;
    private javax.swing.JTextField txtApodo1;
    private javax.swing.JTextField txtDineroInicial;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
