/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;

/**
 *
 * @author BANGHO
 */
public class VentanaJuego extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
    }
    
    public void actualizarPanelSuperior(int partidaActual, int totalPartidas, int rondaActual, double pozo) {
        lblPartida.setText(partidaActual + "/" + totalPartidas);
        lblRonda.setText(rondaActual + "/3"); 
        lblPozo.setText("$" + String.format("%.2f", pozo));
    }

    public void agregarLog(String mensaje) {
        txtLog.append(mensaje + "\n");
        // Auto-scroll
        txtLog.setCaretPosition(txtLog.getDocument().getLength());
    }
    
    public javax.swing.JPanel getPanelJugadores() {
        return panelJugadores;
    }
    
    public void resetearVista() {
        txtLog.setText("");
        panelJugadores.removeAll();
        panelJugadores.revalidate();
        panelJugadores.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblPozo = new javax.swing.JLabel();
        lblPozoTexto = new javax.swing.JLabel();
        lblPartida = new javax.swing.JLabel();
        lblPartidaTexto = new javax.swing.JLabel();
        lblRondaTexto = new javax.swing.JLabel();
        lblRonda = new javax.swing.JLabel();
        panelJugadores = new javax.swing.JPanel();
        panelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGuardarPartida = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRanking = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenuItem();
        menuEstadisticas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la partida"));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPozo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPozo.setText("$0");
        panelSuperior.add(lblPozo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 50, -1));

        lblPozoTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPozoTexto.setText("Pozo:");
        panelSuperior.add(lblPozoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, -1));

        lblPartida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPartida.setText("1/5");
        panelSuperior.add(lblPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 50, -1));

        lblPartidaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPartidaTexto.setText("Partida:");
        panelSuperior.add(lblPartidaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, -1));

        lblRondaTexto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRondaTexto.setText("Ronda:");
        panelSuperior.add(lblRondaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 50, -1));

        lblRonda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRonda.setText("1/3");
        panelSuperior.add(lblRonda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 50, -1));

        getContentPane().add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 70));

        panelJugadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado de jugadores"));
        panelJugadores.setLayout(new java.awt.GridLayout(1, 4));
        getContentPane().add(panelJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 440, 210));

        panelLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log de Eventos"));

        txtLog.setEditable(false);
        txtLog.setColumns(40);
        txtLog.setRows(8);

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(panelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 440, 180));

        jMenu1.setText("Partida");

        menuGuardarPartida.setText("Guardar Partida");
        jMenu1.add(menuGuardarPartida);

        menuSalir.setText("Salir");
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");

        menuRanking.setText("Ranking Actual");
        jMenu2.add(menuRanking);

        menuHistorial.setText("Historial de Partidas");
        jMenu2.add(menuHistorial);

        menuEstadisticas.setText("Estadísticas Generales");
        jMenu2.add(menuEstadisticas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPartida;
    private javax.swing.JLabel lblPartidaTexto;
    private javax.swing.JLabel lblPozo;
    private javax.swing.JLabel lblPozoTexto;
    private javax.swing.JLabel lblRonda;
    private javax.swing.JLabel lblRondaTexto;
    private javax.swing.JMenuItem menuEstadisticas;
    private javax.swing.JMenuItem menuGuardarPartida;
    private javax.swing.JMenuItem menuHistorial;
    private javax.swing.JMenuItem menuRanking;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelJugadores;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
